import { useEffect, useState } from 'react';
import Layout from '../components/Layout';
import { supabase } from '../lib/supabaseClient';

function todayISO(){return new Date().toISOString().slice(0,10)}
function fmtDate(iso){if(!iso)return'';const[y,m,d]=iso.split('-');return`${d}/${m}/${y}`}
const EMOJI_SCALE=[{value:1,emoji:'😟',label:'Poor'},{value:2,emoji:'😐',label:'Satisfactory'},{value:3,emoji:'🙂',label:'Good'},{value:4,emoji:'😊',label:'Very good'},{value:5,emoji:'😄',label:'Excellent'}];
const RATING_FIELDS=['motivation','learning','behaviour'];
const RATING_LABELS={motivation:'Motivation',learning:'Learning',behaviour:'Behaviour'};
const SEDI=['Grosseto','Esterna'];
const CORSI=['Mousy','Linda','Sam','Emma','Oliver','Marcia','Pam & Paul','Ben & Brenda'];
const CORSO_INFO={Mousy:'Mousy (12-36 months, with a parent). IMPORTANT: verbal production is NOT expected. Assess reactivity, attention, simple command response, name recognition, emotional participation. Fussiness/distraction is normal, not a behaviour issue.',Linda:'Linda (2-3 years, parents present early on then independent). First words and short phrases emerging. Assess greetings, age, simple instructions, colours/numbers, counting to 10. Egocentrism/sharing difficulty is normal.',Sam:'Sam (3-4 years). Active participation, answering questions, describing objects, fixed structures in context. Assess greetings, personal questions (I am three), feelings, colour/shape/size description, simple game instructions.',Emma:'Emma (4-5 years). More complex structures, full sentences expected (not single words). Assess greetings, weather, feelings, story questions, counting to 15, object description. Behaviour board in use.',Oliver:'Oliver (5-6 years, may include older beginners). Broader topic vocabulary: rooms, body parts, clothes, daily actions. Assess greetings, weather, feelings/actions, topic vocabulary, spatial placement. Behaviour board in regular use.',Marcia:'Marcia (6-7 years). Advanced course, rich stories, complex structures, dialogues, comparisons, instructions. Full autonomy expected (bathroom alone), sustained concentration for the whole lesson.','Pam & Paul':'Pam & Paul (7-8 years): advanced level. Solid language base, complex structures, narration, dialogic interaction, autonomous language use. Assess active communicative competence, grammatical accuracy, elaborated expression.','Ben & Brenda':'Ben & Brenda (8-9 years): most advanced level. Consolidated proficiency, sophisticated structures, critical thinking in language, elaborated production. Assess structure mastery, expressive creativity, argumentation ability.'};
const GIORNI=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const CURRENT_YEAR='2026-2027';
function emptyEntry(){return{note:'',motivation:null,learning:null,behaviour:null}}

export default function FollowUp(){
const[groups,setGroups]=useState([]),[sessions,setSessions]=useState([]),[allSessions,setAllSessions]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[saveError,setSaveError]=useState(''),[saveOk,setSaveOk]=useState(false);
const[form,setForm]=useState({group_id:'',session_date:todayISO(),story:'',day:'',group_note:''});
const[presentStudents,setPresentStudents]=useState([]),[entries,setEntries]=useState({}),[newStudentName,setNewStudentName]=useState(''),[addingStudent,setAddingStudent]=useState(false),[showAddSuggestions,setShowAddSuggestions]=useState(false);
const[newGroup,setNewGroup]=useState({sede:'Grosseto',corso:'',giorno:'',orario:'',anno_scolastico:CURRENT_YEAR}),[creatingGroup,setCreatingGroup]=useState(false),[groupCreateError,setGroupCreateError]=useState(''),[showNewGroup,setShowNewGroup]=useState(false),[yearFilter,setYearFilter]=useState(CURRENT_YEAR);
const[pdfBase64,setPdfBase64]=useState(''),[pdfName,setPdfName]=useState(''),[generating,setGenerating]=useState(false),[generatingMode,setGeneratingMode]=useState(null),[generateError,setGenerateError]=useState('');
const[studentQuery,setStudentQuery]=useState(''),[selectedStudent,setSelectedStudent]=useState(''),[showSearchSuggestions,setShowSearchSuggestions]=useState(false),[copied,setCopied]=useState(false),[copiedClassroom,setCopiedClassroom]=useState(false);
const availableYears=Array.from(new Set(groups.map(g=>g.anno_scolastico).filter(Boolean))).sort((a,b)=>b.localeCompare(a));if(!availableYears.includes(CURRENT_YEAR))availableYears.unshift(CURRENT_YEAR);
const groupsForYear=groups.filter(g=>g.anno_scolastico===yearFilter);const selectedGroup=groups.find(g=>g.id===form.group_id)||null;const groupStudents=selectedGroup&&Array.isArray(selectedGroup.students)?selectedGroup.students:[];
const studentList=Array.from(new Set(groups.flatMap(g=>Array.isArray(g.students)?g.students:[]))).sort((a,b)=>a.localeCompare(b,'it'));
const addSuggestions=newStudentName.trim()?studentList.filter(n=>n.toLowerCase().includes(newStudentName.trim().toLowerCase())&&n!==newStudentName).slice(0,6):[];
const searchSuggestions=studentQuery.trim()?studentList.filter(n=>n.toLowerCase().includes(studentQuery.trim().toLowerCase())&&n!==studentQuery).slice(0,6):[];
const studentHistory=selectedStudent?allSessions.filter(s=>(s.entries||[]).some(en=>en.name&&en.name.toLowerCase()===selectedStudent.toLowerCase())).sort((a,b)=>new Date(a.session_date)-new Date(b.session_date)):[];
async function loadData(){setLoading(true);const[{data:g},{data:s},{data:all}]=await Promise.all([supabase.from('group_students').select('*').order('sede'),supabase.from('followup_sessions').select('*').order('created_at',{ascending:false}).limit(15),supabase.from('followup_sessions').select('*').order('session_date',{ascending:true}).limit(2000)]);setGroups(g||[]);setSessions(s||[]);setAllSessions(all||[]);setLoading(false)}
useEffect(()=>{loadData()},[]);useEffect(()=>{setPresentStudents(groupStudents);setEntries({})},[form.group_id]);
function getEntry(name){return entries[name]||emptyEntry()}function setEntryPatch(name,patch){setEntries(prev=>({...prev,[name]:{...getEntry(name),...patch}}))}function togglePresent(name){setPresentStudents(prev=>prev.includes(name)?prev.filter(n=>n!==name):[...prev,name])}
async function upsertGroupStudents(group,students){const{error}=await supabase.from('group_students').update({students}).eq('id',group.id);if(error)setGroupCreateError('Error saving students: '+error.message);return!error}
async function handleAddStudent(){const name=newStudentName.trim();if(!name||!selectedGroup||groupStudents.includes(name))return;setAddingStudent(true);await upsertGroupStudents(selectedGroup,[...groupStudents,name]);setNewStudentName('');setAddingStudent(false);await loadData()}
async function handleRemoveStudent(name){if(!selectedGroup)return;await upsertGroupStudents(selectedGroup,groupStudents.filter(n=>n!==name));await loadData()}
async function handleCreateGroup(){if(!newGroup.corso||!newGroup.giorno)return;setCreatingGroup(true);setGroupCreateError('');const{data,error}=await supabase.from('group_students').insert({sede:newGroup.sede,corso:newGroup.corso,giorno:newGroup.giorno,orario:newGroup.orario||'',anno_scolastico:newGroup.anno_scolastico||CURRENT_YEAR,students:[]}).select().single();setCreatingGroup(false);if(error){setGroupCreateError(error.code==='23505'?'This group already exists — select it from the list above.':'Error: '+error.message);return}await loadData();setYearFilter(data.anno_scolastico);setForm(f=>({...f,group_id:data.id}));setShowNewGroup(false);setNewGroup({sede:'Grosseto',corso:'',giorno:'',orario:'',anno_scolastico:CURRENT_YEAR})}
function copyHistory(){const lines=[selectedStudent,''];studentHistory.forEach(session=>{const entry=(session.entries||[]).find(en=>en.name&&en.name.toLowerCase()===selectedStudent.toLowerCase());if(!entry||!entry.note)return;lines.push(`${fmtDate(session.session_date)} — ${session.corso||''} ${session.giorno||''}`.trim(),entry.note,'')});navigator.clipboard.writeText(lines.join('\n').trim()||'No individual note found for this student.');setCopied(true);setTimeout(()=>setCopied(false),2000)}
function copyForClassroom(){const lines=[];if(form.group_note.trim())lines.push('GROUP NOTE:',form.group_note.trim(),'');presentStudents.forEach(name=>{const entry=getEntry(name);if(entry.note)lines.push(`${name}:`,entry.note,'')});navigator.clipboard.writeText(lines.join('\n').trim()||'No notes to copy yet — generate or write some first.');setCopiedClassroom(true);setTimeout(()=>setCopiedClassroom(false),2000)}
function selectedGroupLabel(){return selectedGroup?`${selectedGroup.sede} · ${selectedGroup.corso} · ${selectedGroup.giorno}`:''}
async function handleSubmit(e){e.preventDefault();setSaveError('');setSaveOk(false);if(!form.group_id){setSaveError('Select a group.');return}setSaving(true);const entryList=presentStudents.map(name=>({name,...getEntry(name)}));const{error}=await supabase.from('followup_sessions').insert({group_id:form.group_id,group_name:selectedGroupLabel(),session_date:form.session_date,story:form.story||null,day:form.day||null,group_note:form.group_note||null,sede:selectedGroup?.sede||null,corso:selectedGroup?.corso||null,giorno:selectedGroup?.giorno||null,orario:selectedGroup?.orario||null,anno_scolastico:selectedGroup?.anno_scolastico||null,entries:entryList});setSaving(false);if(error){setSaveError('Error saving: '+error.message);return}setSaveOk(true);setForm({group_id:'',session_date:todayISO(),story:'',day:'',group_note:''});setPresentStudents([]);setEntries({});loadData()}
async function handleDeleteGroup(group){if(!window.confirm(`Delete the group ${group.sede} · ${group.corso} · ${group.giorno}${group.orario?' · '+group.orario:''}? The students and linked follow-ups will not be affected, but the group will disappear from the list.`))return;const{error}=await supabase.from('group_students').delete().eq('id',group.id);if(error){alert('Delete error: '+error.message);return}if(form.group_id===group.id)setForm(f=>({...f,group_id:''}));await loadData()}
async function handleDeleteSession(session){if(!window.confirm(`Delete the follow-up from ${fmtDate(session.session_date)} (${session.group_name})?`))return;const{error}=await supabase.from('followup_sessions').delete().eq('id',session.id);if(error){alert('Delete error: '+error.message);return}await loadData()}
function handlePdfChange(e){const file=e.target.files?.[0];if(!file)return;setPdfName(file.name);const reader=new FileReader();reader.onload=()=>setPdfBase64(String(reader.result||'').split(',')[1]||'');reader.readAsDataURL(file)}function clearPdf(){setPdfBase64('');setPdfName('')}
function buildPrompt(mode){const present=presentStudents;const corsoContext=(selectedGroup&&CORSO_INFO[selectedGroup.corso])||`Corso: ${selectedGroup?.corso||''}`;const pdfCtx=pdfBase64?'Il PDF della lezione è allegato — leggilo per capire le attività svolte e gli obiettivi didattici del giorno.':'';const noteCtx=form.group_note.trim()?`\nNota generale: "${form.group_note}"`:'';if(mode==='fromNote')return`Sei un assistente per insegnanti Kids&Us in Italia. Genera valutazioni interne per uso esclusivo dell'insegnante (base per le pagelle).\n\nPROFILO DEL CORSO:\n${corsoContext}\n\n${pdfCtx}${noteCtx}\nAllievi presenti: ${present.join(', ')}.\n\nPer ciascun allievo presente genera:\n1. Nota valutativa in italiano di 2-3 frasi (professionale, oggettiva, calibrata sull'età e il livello del corso, basata sulle attività del PDF)\n2. Valore 1-5 per: motivation, learning, behaviour. Scala: 1=Poor 2=Satisfactory 3=Good 4=Very good 5=Excellent\n\nRispondi SOLO con JSON valido senza markdown.`;const ratingsDesc=present.map(name=>{const e=getEntry(name),parts=[];if(e.motivation)parts.push(`motivation: ${EMOJI_SCALE.find(x=>x.value===e.motivation)?.label}`);if(e.learning)parts.push(`learning: ${EMOJI_SCALE.find(x=>x.value===e.learning)?.label}`);if(e.behaviour)parts.push(`behaviour: ${EMOJI_SCALE.find(x=>x.value===e.behaviour)?.label}`);return`${name}: ${parts.length?parts.join(', '):'nessuna valutazione'}`}).join('\n');return`Sei un assistente per insegnanti Kids&Us in Italia. Genera note valutative interne basandoti sulle valutazioni emoji dell'insegnante.\n\nPROFILO DEL CORSO:\n${corsoContext}\n\n${pdfCtx}${noteCtx}\n\nValutazioni emoji:\n${ratingsDesc}\n\nPer ciascun allievo scrivi nota in italiano di 2-3 frasi coerente con i livelli indicati. Rispondi SOLO con JSON valido senza markdown.`}
async function handleGenerate(mode){setGenerateError('');if(!presentStudents.length){setGenerateError('Segna almeno un allievo come presente.');return}if(mode==='fromNote'&&!form.group_note.trim()&&!pdfBase64){setGenerateError('Carica il PDF della lezione o scrivi una nota di gruppo.');return}if(mode==='fromEmoji'&&!presentStudents.some(n=>{const e=getEntry(n);return e.motivation||e.learning||e.behaviour})){setGenerateError("Assegna almeno un'emoji a qualche allievo.");return}setGenerating(true);setGeneratingMode(mode);const messages=[pdfBase64?{role:'user',content:[{type:'document',source:{type:'base64',media_type:'application/pdf',data:pdfBase64}},{type:'text',text:buildPrompt(mode)}]}:{role:'user',content:buildPrompt(mode)}];try{const resp=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:'claude-sonnet-4-6',max_tokens:3000,messages})});const data=await resp.json();const parsed=JSON.parse((data.content||[]).map(b=>b.text||'').join('').replace(/```json|```/g,'').trim());if(mode==='fromNote')presentStudents.forEach(name=>{const r=parsed[name];if(!r)return;setEntryPatch(name,typeof r==='object'?{note:r.note||'',motivation:r.motivation||null,learning:r.learning||null,behaviour:r.behaviour||null}:{note:String(r)})});else presentStudents.forEach(name=>{if(parsed[name])setEntryPatch(name,{note:parsed[name]})})}catch(e){setGenerateError('Error: '+e.message)}setGenerating(false);setGeneratingMode(null)}
return <Layout><div className="page-eyebrow">Active module</div><h1 className="page-title">Follow-up</h1><p className="page-desc">Record today's note and check the group's history.</p>
<div className="section-block"><h2>New follow-up</h2><form onSubmit={handleSubmit}><div className="field"><label>School year</label><select value={yearFilter} onChange={e=>setYearFilter(e.target.value)}>{availableYears.map(y=><option key={y}>{y}</option>)}</select></div><div className="field"><label>Group</label><select value={form.group_id} onChange={e=>setForm({...form,group_id:e.target.value})}><option value="">Select…</option>{groupsForYear.map(g=><option key={g.id} value={g.id}>{g.sede} · {g.corso} · {g.giorno}{g.orario?` · ${g.orario}`:''}</option>)}</select>{!showNewGroup?<button type="button" className="btn secondary" style={{marginTop:8,alignSelf:'flex-start'}} onClick={()=>setShowNewGroup(true)}>+ New group</button>:<div style={{marginTop:8,display:'flex',gap:8,flexWrap:'wrap',alignItems:'center',background:'#fff',border:'1px solid var(--line)',borderRadius:10,padding:10}}><select value={newGroup.sede} onChange={e=>setNewGroup({...newGroup,sede:e.target.value})}>{SEDI.map(s=><option key={s}>{s}</option>)}</select><select value={newGroup.corso} onChange={e=>setNewGroup({...newGroup,corso:e.target.value})}><option value="">Course…</option>{CORSI.map(c=><option key={c}>{c}</option>)}</select><select value={newGroup.giorno} onChange={e=>setNewGroup({...newGroup,giorno:e.target.value})}><option value="">Day…</option>{GIORNI.map(g=><option key={g}>{g}</option>)}</select><input placeholder="Time" value={newGroup.orario} onChange={e=>setNewGroup({...newGroup,orario:e.target.value})}/><input placeholder="School year" value={newGroup.anno_scolastico} onChange={e=>setNewGroup({...newGroup,anno_scolastico:e.target.value})} style={{width:100}}/><button type="button" className="btn" onClick={handleCreateGroup} disabled={creatingGroup||!newGroup.corso||!newGroup.giorno}>Create</button><button type="button" className="btn secondary" onClick={()=>setShowNewGroup(false)}>Cancel</button>{groupCreateError&&<div className="error-text" style={{width:'100%'}}>{groupCreateError}</div>}</div>}</div><div className="field"><label>Date</label><input type="date" value={form.session_date} onChange={e=>setForm({...form,session_date:e.target.value})}/></div><div className="field"><label>Story / Day</label><input placeholder="e.g. Story 2, Day 4" value={form.story} onChange={e=>setForm({...form,story:e.target.value})}/></div>
{selectedGroup&&<div className="field"><label>Attendance — {groupStudents.length} students</label><div style={{display:'flex',flexWrap:'wrap',gap:8,marginBottom:10}}>{groupStudents.map(name=>{const present=presentStudents.includes(name);return <span key={name} style={{display:'inline-flex',alignItems:'center',gap:4}}><button type="button" onClick={()=>togglePresent(name)} className="btn secondary" style={{padding:'6px 12px',background:present?'#e9f1ea':'transparent',color:present?'#5f8567':'#5a6270'}}>{present?'✓ ':'✗ '}{name}</button><button type="button" onClick={()=>handleRemoveStudent(name)} style={{border:'none',background:'none',color:'#e1573a'}}>×</button></span>})}</div><div style={{position:'relative'}}><div style={{display:'flex',gap:8}}><input placeholder="New student name…" value={newStudentName} onChange={e=>{setNewStudentName(e.target.value);setShowAddSuggestions(true)}} onFocus={()=>setShowAddSuggestions(true)} onBlur={()=>setTimeout(()=>setShowAddSuggestions(false),150)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();handleAddStudent()}}} style={{flex:1}}/><button type="button" className="btn secondary" onClick={handleAddStudent} disabled={addingStudent}>+ Add</button></div>{showAddSuggestions&&addSuggestions.length>0&&<div style={{position:'absolute',top:'100%',left:0,right:0,zIndex:10,background:'#fff',border:'1px solid var(--line)',borderRadius:10}}>{addSuggestions.map(n=><div key={n} onMouseDown={()=>{setNewStudentName(n);setShowAddSuggestions(false)}} style={{padding:'10px 12px'}}>{n}</div>)}</div>}</div></div>}
{presentStudents.length>0&&<div className="field"><label>Individual assessments</label>{presentStudents.map(name=>{const entry=getEntry(name);return <div key={name} style={{border:'1px solid var(--line)',borderRadius:10,padding:12,marginBottom:10,background:'#fff'}}><strong>{name}</strong>{RATING_FIELDS.map(field=><div key={field} style={{display:'flex',alignItems:'center',gap:6,marginTop:8}}><span style={{fontSize:12,width:80}}>{RATING_LABELS[field]}</span>{EMOJI_SCALE.map(es=><button key={es.value} type="button" title={es.label} onClick={()=>setEntryPatch(name,{[field]:entry[field]===es.value?null:es.value})} style={{border:entry[field]===es.value?'2px solid var(--coral)':'1px solid var(--line)',borderRadius:8,background:'#fff',padding:'2px 6px',fontSize:16}}>{es.emoji}</button>)}</div>)}<textarea placeholder="Individual note…" value={entry.note} onChange={e=>setEntryPatch(name,{note:e.target.value})} style={{width:'100%',marginTop:8,minHeight:50}}/></div>})}</div>}
{selectedGroup&&presentStudents.length>0&&<div className="field"><label>Generate with AI</label><div style={{border:'1px solid var(--line)',borderRadius:10,padding:12,background:'#fff'}}><div style={{display:'flex',gap:10,marginBottom:10,flexWrap:'wrap'}}><label htmlFor="pdf-upload" className="btn secondary">{pdfName?'📄 Change PDF':'📄 Upload lesson PDF'}</label><input id="pdf-upload" type="file" accept=".pdf,application/pdf" onChange={handlePdfChange} style={{display:'none'}}/>{pdfName&&<><span>{pdfName}</span><button type="button" onClick={clearPdf}>remove</button></>}</div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button type="button" className="btn" disabled={generating} onClick={()=>handleGenerate('fromNote')}>{generating&&generatingMode==='fromNote'?'Generating…':'Generate notes + assessments from PDF/note'}</button><button type="button" className="btn secondary" disabled={generating} onClick={()=>handleGenerate('fromEmoji')}>{generating&&generatingMode==='fromEmoji'?'Generating…':'Generate notes from chosen emojis'}</button></div>{generateError&&<div className="error-text">{generateError}</div>}</div></div>}
{presentStudents.length>0&&<button className="btn secondary" type="button" onClick={copyForClassroom}>{copiedClassroom?'Copied ✓':'📋 Copy notes for myclassroom'}</button>}<div className="field" style={{marginTop:16}}><label>Group note (optional)</label><textarea value={form.group_note} onChange={e=>setForm({...form,group_note:e.target.value})}/></div>{saveError&&<div className="error-text">{saveError}</div>}{saveOk&&<div style={{color:'#5f8567'}}>Saved.</div>}<button className="btn" type="submit" disabled={saving}>{saving?'Saving…':'Save follow-up'}</button></form></div>
<div className="section-block"><h2>Student history</h2><div className="field" style={{position:'relative'}}><label>Search student</label><input value={studentQuery} onChange={e=>{setStudentQuery(e.target.value);setShowSearchSuggestions(true);const exact=studentList.find(n=>n.toLowerCase()===e.target.value.toLowerCase());setSelectedStudent(exact||'')}} onFocus={()=>setShowSearchSuggestions(true)} onBlur={()=>setTimeout(()=>setShowSearchSuggestions(false),150)}/>{showSearchSuggestions&&searchSuggestions.length>0&&<div style={{position:'absolute',top:'100%',left:0,right:0,zIndex:10,background:'#fff',border:'1px solid var(--line)'}}>{searchSuggestions.map(n=><div key={n} onMouseDown={()=>{setStudentQuery(n);setSelectedStudent(n);setShowSearchSuggestions(false)}} style={{padding:'10px 12px'}}>{n}</div>)}</div>}</div>{selectedStudent&&<><div style={{display:'flex',justifyContent:'space-between',marginBottom:12}}><strong>{selectedStudent}</strong><button className="btn secondary" onClick={copyHistory} type="button">{copied?'Copied ✓':'Copy all for Term Reports'}</button></div>{studentHistory.length===0?<p className="page-desc">No follow-up found for this student yet.</p>:<table className="simple-table"><thead><tr><th>Date</th><th>Group</th><th>Assessments</th><th>Note</th></tr></thead><tbody>{studentHistory.map(s=>{const entry=(s.entries||[]).find(en=>en.name&&en.name.toLowerCase()===selectedStudent.toLowerCase());const ratings=entry?RATING_FIELDS.map(f=>entry[f]&&EMOJI_SCALE.find(x=>x.value===entry[f])?.emoji).filter(Boolean).join(' '):'';return <tr key={s.id}><td>{fmtDate(s.session_date)}</td><td>{s.corso} · {s.giorno}</td><td>{ratings||'—'}</td><td>{entry?.note||'—'}</td></tr>})}</tbody></table>}</>}</div>
<div className="section-block"><h2>Your groups</h2>{loading?<p className="page-desc">Loading…</p>:<table className="simple-table"><thead><tr><th>Location</th><th>Course</th><th>Day</th><th>Time</th><th>Year</th><th>Students</th><th></th></tr></thead><tbody>{groups.map(g=><tr key={g.id}><td>{g.sede}</td><td>{g.corso}</td><td>{g.giorno}</td><td>{g.orario||'—'}</td><td>{g.anno_scolastico}</td><td>{Array.isArray(g.students)?g.students.length:0}</td><td><button type="button" onClick={()=>handleDeleteGroup(g)} className="link-btn danger">Delete</button></td></tr>)}</tbody></table>}</div>
<div className="section-block"><h2>Recent follow-ups</h2>{loading?<p className="page-desc">Loading…</p>:<table className="simple-table"><thead><tr><th>Date</th><th>Group</th><th>Story/Day</th><th>Students assessed</th><th></th></tr></thead><tbody>{sessions.map(s=><tr key={s.id}><td>{fmtDate(s.session_date)}</td><td>{s.group_name}</td><td>{s.story||'—'}</td><td>{Array.isArray(s.entries)?s.entries.length:0}</td><td><button type="button" onClick={()=>handleDeleteSession(s)} className="link-btn danger">Delete</button></td></tr>)}</tbody></table>}</div></Layout>}
